### ISSUE TITLE
Comparison with bs-webapi-incubator

### ISSUE THREAD

**Issue by Risto-Stevcev** [yawaramin/bs-webapi#1]
What's the comparison of this lib with bs-webapi-incubator?

https://github.com/reasonml-community/bs-webapi-incubator

**Comment by yawaramin** [comment]
Hey Risto, I wrote a little bit about that here: https://yawaramin.github.io/bs-webapi/#1_Why . Does that clarify things?

**Comment by Risto-Stevcev** [comment]
Ah nice, I've been thinking about the same thing too! :)

A while ago I accidentally started writing some web apis before I knew about that repo, so I was already thinking about the inheritance and everything. I think their approach is really interesting, I never thought to use functors like that, but after using it for a while I find it really verbose.

Inheritance is supposed to be all about succinctness because it knows where it needs to dispatch to, but with webapi-incubator the constant converting to and from types gets really annoying and hard to read.

Have you thought about using poly variants or ocaml's object system (row polymorphism)?
I've been working on a declarative dom markup lib for a few months now, it's still a WIP but it's close to being done:

https://github.com/Risto-Stevcev/bs-declaredom

I ended up leveraging poly variants to enforce some important HTML and CSS relationships:
- The relationships between different CSS properties and which kind of displays it applies to. For example, `vertical-align` applies to inline elements, so you shouldn't be able to apply it to other elements like block elements
- The relationships between different HTML elements and the kind of children they can take. For example, `<div>` is a generic flow container, so it should only take children that belong to the flow content category.

I like a lot about Ocaml because of it's features, but I think poly variants are now at the top of the list. No other statically typed language has given me the ability to be that expressive and still be sound from a type system perspective

**Comment by yawaramin** [comment]
Hey so I thought about using the object system, as you said, but you quickly run into issues when trying to do FFI. For example, here's a little sample I came up with for the `EventTarget` type, the top of the hierarchy:

```ocaml
type _ event
type 'a eventHandler = 'a event -> unit [@bs]
type 'a eventListener = < handleEvent: 'a eventHandler > Js.t

class type _eventTarget = object
  method addEvent'Listener'options: string -> 'a eventListener -> < capture: bool; once: bool; passive: bool > Js.t -> unit [@bs.as "addEventListener"]
  method addEvent'Listener'useCapture: string -> 'a eventListener -> bool -> unit [@bs.as "addEventListener"]
  method addEvent'Handler'options: string -> 'a eventHandler -> < capture: bool; once: bool; passive: bool > Js.t -> unit [@bs.as "addEventListener"]
  method addEvent'Handler'useCapture: string -> 'a eventHandler -> bool -> unit [@bs.as "addEventListener"]
end [@bs]

type eventTarget = _eventTarget Js.t
```

This is considerably less ergonomic than the normal modules-and-functions approach. And I'm not actually sure this will work! I think the upshot is that BuckleScript by choice has less support for OOP-style bindings, and that's OK, it encourages a functional style and you can go quite far with modules, functors, functions, and the data type zoo.

Your declarative markup style reminds me of tyxml, see e.g. https://github.com/ocsigen/tyxml/blob/8ff19c0989f201043f5f4a7c94ee7a6bcb79bb13/lib/html_types.mli . Especially trying to constrain things like 'div can only contain flow content', etc.

**Comment by Risto-Stevcev** [comment]
What about poly variants? something like:

_src/demo.ml_
```ocaml
module Type = struct
  type comment and document and html_element and svg_element and text and window
end

type comment = [ `comment of Type.comment ]
type document = [ `document of Type.document ]
type html_element = [ `html_element of Type.html_element ]
type svg_element = [ `svg_element of Type.svg_element ]
type text = [ `text of Type.text ]
type window = [ `window of Type.window ]

type element = [ html_element | svg_element ]
type character_data = [ comment | text ]
type node = [ character_data | document | element ]
type event_target = [ node | window ]

type event
external addEventListener:
  [< event_target] -> string -> (event -> unit) -> unit = "" [@@bs.send]

external window: window = "" [@@bs.val]
external document: document = "" [@@bs.val]
external body: html_element = "" [@@bs.scope "document"] [@@bs.val]

let _ =
  addEventListener body "click" (fun _ -> Js.log "clicked body");
  addEventListener window "blur" (fun _ -> Js.log "window blurred");
  addEventListener document "DOMContentLoaded" (fun _ -> Js.log "dom loaded");
```

_src/index.html_
```html
<!doctype html>
<html>
  <body>
    <span>hello world</span>
    <script src="./demo.bs.js"></script>
  </body>
</html>
```
```sh
$ parcel src/index.html
```

Though i'm not sure you'd need the `Type.` if the variants are parameterized by an abstract type with a phantom param. Thanks for mentioning tyxml, I noticed their style is similar but a little different because they don't parameterize the variants with another abstract type. It's possible I didn't need the `Type.` part in the variant since `Css_Proeprty.t` and `Node.t` are abstract types, but I feel like I remember a particularly good reason for having it in there. But I also went through a lot of iterations, maybe I wasn't thinking clearly or it was part of some earlier design that got thrown away :-/

**Comment by yawaramin** [comment]
What I wanted to do was avoid having supertypes know about their subtypes. So from your example:

```ocaml
type event_target = [ node | window ]
```

We'd need to modify this every time we added a new subtype. The approach I took (from Fred Bour's Qt bindings, Cuite actually, although others have probably used the same technique) is to model the subtyping relationship using an abstract type `'a t` and a polymorphic variant type variable to model its exact subtype. This works using a neat dualism: polymorphic variants in covariant position model _union_ types, but in contravariant position model _intersection_ types! So e.g. (assuming `open EventTarget`):

```ocaml
[`eventTarget | `node | `element] t <: [`eventTarget | `node] t <: [`eventTarget] t
```

Or using my aliases,

```ocaml
Element.this t <: Node.this t <: this t
```

**Comment by Risto-Stevcev** [comment]
That's interesting. Are you thinking something like this?

```ocaml
type 'a t

external window: [`window | `eventTarget] t = "" [@@bs.val]
external document: [`document | `element | `node | `eventTarget] t = ""
[@@bs.val]
external body: [`body | `html_element | `element | `node | `eventTarget] t = ""
[@@bs.scope "document"] [@@bs.val]

external addEventListener:
  [> `eventTarget] t -> string -> (event -> unit) -> unit = "" [@@bs.send]

let _ =
  addEventListener body "click" (fun _ -> Js.log "clicked body");
  addEventListener window "blur" (fun _ -> Js.log "window blurred");
  addEventListener document "DOMContentLoaded" (fun _ -> Js.log "dom loaded");
```

I ran into the same issue, but I figured that the html and css specs won't change much, and if they do the lib deserves a major version bump anyway so breaking changes are ok. But I ran into the issue again thinking about custom types a la web components. I was thinking of just adding an 'a for custom elements like
```type 'a custom = [`custom of 'a]```
and have the signatures that accept `custom` just accept `'a custom`, so any new custom elements that get added work ok, like if someone writes `foo custom`, it works with existing code. But I really don't like that solution, and besides what if people extend an existing element like `<input>`? which is to be expected.
I like your idea, it does look like it's the most flexible solution

**Comment by yawaramin** [comment]
Yeah, exactly like that! The compiler checks the validity of operations by trying to find a common intersection between the polymorphic variant sets. I haven't thought about Web Components too much, it will be interesting to figure out how to type them. The `'a custom` approach looks similar to BuckleScript's included DOM types (in the `Dom` module), also touched on a bit over here: https://github.com/reasonml-community/bs-webapi-incubator#subtyping . In fact, looking at that just now and its linked PR, I just realized that my approach also supports multiple inheritance (just smash together two different poly variant types) whereas the BuckleScript `Dom` approach doesn't.

**Comment by Risto-Stevcev** [comment]
Nice :slightly_smiling_face: 

I don't think this will work for my use case though. Specifically it doesn't let me describe these kind of semantics:
```ocaml
module Div = struct
  type 'a child = 'a Html_Node.t constraint 'a = [> Html_Node.flow]
end
module Span = struct
  type 'a child = 'a Html_Node.t constraint 'a = [> Html_Node.phrasing | Html_Node.other ]
  (* ... *)
end
```
Note that `Div.child` can select for things fine such as 
```ocaml
type span = [ `span | `flow | `phrasing ]
```
 but if an element takes multiple content categories as children like `Span.child` does, which is more often than not, then I'm out of luck


I think that's why I ended up with this kind of thing in my code:
```ocaml
type comment = [ `comment of Type.comment ]
```

**Comment by Risto-Stevcev** [comment]
And the reason why getting rid of `Type` and using something like `Html_Node.flow Html_Node.t` doesn't work is because of the value restriction:
```sh
  This expression's type contains type variables that can't be generalized:
```
```ocaml
  Html_Node.t(_[> Html_Node.div ])
```

I'm not sure why ocaml is value resticting this version but not my current
```ocaml
type comment = [ `comment of Type.comment ]
```
I wish I knew why

**Comment by yawaramin** [comment]
Interesting. If you have an MCVE I'd love to take a look at it.

**Comment by Risto-Stevcev** [comment]
```ocaml
module PolyInvertedContravariant = struct
  type 'a t

  type flow = [ `flow ]
   and phrasing = [ `phrasing ]
   and none = [ `none ]

  type div = [ `div | flow ]
   and span = [ `span | flow | phrasing ]
   and option = [ `option | none ]
   and datalist = [ `datalist | flow | phrasing ]

  module Test = struct
    (* Doesn't work, can't unify [`option | `none] with [`flow | `none] *)
    let span (children: [< flow | none ] t array): span t = Obj.magic children
    let datalist (children: [< phrasing | option ] t array): datalist t =
      Obj.magic children

    let ex_option: option t = Obj.magic ()
    let ex_span = span [|ex_option|]
    let ex_datalist = datalist [|ex_option; ex_span|]
  end

  module Test' = struct
    (* Opening variants works but this is value restricted, and the children
     * take an open variant which is wrong *)
    let span (children: [> flow | none ] t array): [> span] t = Obj.magic children
    let datalist (children: [> phrasing | option ] t array): [> datalist] t =
      Obj.magic children

    let ex_option: [> option] t = Obj.magic ()
    let ex_span = span [|ex_option|]
    let ex_datalist = datalist [|ex_option; ex_span|]
  end
end


module PolyGroupContravariant = struct
  type 'a t

  type div = [ `div ]
   and span = [ `span ]
   and option = [ `option ]
   and datalist = [ `datalist ]

  type none = option

  type flow = [ div | span | datalist | none ]
   and phrasing  = [ span | datalist | none ]

  module Test = struct
    let span (children: [< flow ] t array): span t = Obj.magic children
    let datalist (children: [< phrasing | option ] t array): datalist t =
      Obj.magic children

    let ex_option: option t = Obj.magic ()
    let ex_span = span [|ex_option|]
    (* The children array can't unify here due to the monotype restriction *)
    let ex_datalist = datalist [|ex_option; ex_span|]
  end

  module Test' = struct
    let span (children: [< flow ] t array): [> span] t = Obj.magic children
    let datalist (children: [< phrasing | option ] t array): [> datalist] t =
      Obj.magic children

    let ex_option: [> option] t = Obj.magic ()
    let ex_span = span [|ex_option|]
    (* This works but this is value restricted *)
    let ex_datalist = datalist [|ex_option; ex_span|]
  end
end


module PolyGroupCovaraint = struct
  module Type = struct
    type div and span and option and datalist
  end

  type 'a t

  type div = [ `div of Type.div ]
   and span = [ `span of Type.span ]
   and option = [ `option of Type.option ]
   and datalist = [ `datalist of Type.datalist ]

  type none = option

  type flow = [ div | span | datalist | none ]
   and phrasing  = [ span | datalist | none ]


  module Test = struct
    let span (children: [< flow ] array): [> span] = Obj.magic children
    let datalist (children: [< phrasing | option ] array): [> datalist] =
      Obj.magic children

    let ex_option: [> option] = Obj.magic ()
    let ex_span = span [|ex_option|]
    (* This works and is _not_ value restricted *)
    let ex_datalist = datalist [|ex_option; ex_span|]
  end
end
```

**Comment by Risto-Stevcev** [comment]
What's happening with the value restriction is that ocaml is inferring `type 'a t` to be invariant and so if I have `a` as a subtype of `b` (`a <= b`) then `t(a) <> t(b)` and the type checker value restricts to `t(_a)`. If I annotate it as covariant then it works:
```ocaml
type +'a t
```
Because now I'm telling ocaml that if `a <= b` then `t(a) <= t(b)`. Interestingly, it seems to inferring it like that only for abstract types. If I do something like this:
```ocaml
type 'a t = Foo of 'a
```
Then it also works fine

You can also see the difference also if you change from `type 'a t = 'a list` to `type 'a t = 'a array`. In ocaml `list` is immutable so the `'a` is covariant, but `array`s are mutable so it's invariant and has the value restriction on `'a`

_edited*_
